server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.128.123:8761/eureka/
  # 自定义实例编号
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

# enable service register
zrpc:
  service: true
  # zookeeper server address
  register:
    zkServeres: 127.0.0.1:2181
    # zookeeper connect timeout
    timeout: 30000
  # RPC server monitor port
  servicePort: 9988

